### ISSUE TITLE
The requested package chumakovanton/yii2-tinkoff-pay could not be found in any version, there may be a typo in the package name.

### ISSUE THREAD

**Issue by craigy-waigy** [ChumakovAnton/yii2-tinkoff-pay#1]
Доброго времени суток! 

Подскажите, как решить проблему с данной ошибкой? Возникает при попытке установки компонента. 
'The requested package chumakovanton/yii2-tinkoff-pay could not be found in any version, there may be a typo in the package name.'

Поставил в composer.json 
"minimum-stability": "dev",
"chumakovanton/yii2-tinkoff-pay": "dev"
но не помогло.

**Comment by ChumakovAnton** [comment]
Попробуйте указать версию "dev-master"
"chumakovanton/yii2-tinkoff-pay": "dev-master"

**Comment by craigy-waigy** [comment]
could not be resolved to an installable set of packages.

  Problem 1
    - The requested package chumakovanton/yii2-tinkoff-pay could not be
found in any version, there may be a typo in the package name.

Potential causes:
 - A typo in the package name
 - The package is not available in a stable-enough version according to
your minimum-stability setting
   see <https://getcomposer.org/doc/04-schema.md#minimum-stability> for
more details.

Read <https://getcomposer.org/doc/articles/troubleshooting.md> for further
common problems.


2018-04-24 17:47 GMT+05:00 Anton Chumakov <notifications@github.com>:

**Comment by ChumakovAnton** [comment]
@craigy-waigy Действительно. Извините. Я забыл выложить проект в packagist. 
В своём проекте я использовал 
`"repositories":[
        {
            "type": "git",
            "url": "https://github.com/ChumakovAnton/yii2-tinkoff-pay"
        }
    ]`
Но сейчас я добавил проект в packagist, поэтому всё должно получиться без добавления секции repositories :-)

**Comment by craigy-waigy** [comment]
​Да, спасибо, установилось.

Можете подсказать, почему может возникать ошибка "Return value of
chumakovanton\tinkoffPay\response\ResponseInit::getPaymentUrl() must be of
the type string, null returned"

Код:
        $paymentService = Yii::$app->tinkoffPay;

        $paymentRequest = new RequestInit('order1', 1);

        $paymentRequest->addData('user_id', Yii::$app->user->id);

        $response = $paymentService->initPay($paymentRequest);

        $paymentUrl = $response->getPaymentUrl();

Запускаю тот скрипт, что предложен на сайте тинькова - урл возвращается ок.
То есть не в настройках дело. В чем то другом, видимо.

4 мая 2018 г., 21:06 пользователь Anton Chumakov <notifications@github.com>
написал:

**Comment by ChumakovAnton** [comment]
@craigy-waigy Это из-за того, что я жестко зафиксировал тип, возвращаемый функцией. Исправил, попробуйте обновить версию.

**Comment by lllyx1** [comment]
Installation failed, reverting ./composer.json to its original content. 
при загрузке через композер composer require --prefer-dist chumakovanton/yii2-tinkoff-pay "*"
